# Generated by Django 5.1.7 on 2025-06-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
