# Generated by Django 5.1.7 on 2025-12-01 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='privacidad',
            field=models.CharField(choices=[('publico', 'Público'), ('amigos', 'Solo amigos'), ('privado', 'Privado')], default='publico', max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='am.publicacion')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('spam', 'Spam'), ('acoso', 'Acoso'), ('contenido_inapropiado', 'Contenido inapropiado'), ('otro', 'Otro')], max_length=25)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('publicacion_reportada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='am.publicacion')),
                ('reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_hechos', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario_solicitante', 'usuario_receptor')},
            },
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('usuario_bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueado_por', to=settings.AUTH_USER_MODEL)),
                ('usuario_bloqueador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_bloqueados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario_bloqueador', 'usuario_bloqueado')},
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Me gusta'), ('love', 'Me encanta'), ('dislike', 'No me gusta')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='am.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('publicacion', 'usuario')},
            },
        ),
    ]
