# Generated by Django 4.2.27 on 2025-12-12 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0005_perfil_telefono_tokenrecuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='es_compartida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='publicacion_compartida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartidas', to='am.publicacion'),
        ),
    ]
